Add ${VARIANT} to module load log message
INM-6/Builder pull request #58
Opened 2022-06-13 14:18 UTC by akorgor

2022-11-14 16:13 UTC, terhorstd reviewed
Is this actually required? For me the modules load without giving a variant. Maybe this is also a difference between the TCL and LMOD systems. On which one did you try this?

2022-12-05 11:28 UTC, akorgor commented
Could be related to this issue. Tried it on JURECA-DC, which has LMOD.

2023-01-12 10:29 UTC, terhorstd commented on build_functions.sh
> +			log_success ">>> use 'module avail' to see and e.g. 'module load ${PACKAGE}/${VERSION}/${VARIANT}' to load modules."
```suggestion
			log_success ">>> use 'module avail' to see and e.g. 'module load ${PACKAGE}/${VERSION}' to load modules,"
			log_success ">>> or 'module load ${PACKAGE}/${VERSION}/${VARIANT}'"
```

2023-01-12 10:31 UTC, terhorstd requested changes
Still not sure about this one, but since it's a so tiny change and it doesn't break anything I'm inclined to just put it in. I also didn't come across more lmod-vs-tcl things recently.

2023-01-16 12:55 UTC, akorgor commented
Giving both would be indeed a good solution.

2023-01-19 15:38 UTC, terhorstd approved these changes
:+1: This should be fine for now. Still fighting myself to understand the full implications of the version/variant syntax in LMOD, but that shouldn't stop us here.

2024-09-06 14:29 UTC, akorgor commented
@terhorstd Should I merge or close this old PR?

2026-04-26 07:11 UTC, closed without merging